version: "3"

services:
  mysql:
    image: mysql:8
    environment:
      MYSQL_DATABASE: "hshop"
      MYSQL_ROOT_PASSWORD: "tF8jtP#zdz"
    ports:
      - 3306:3306
    restart: always
    networks:
      - hshop-network
    volumes:
      - mysql:/var/lib/mysql

  redis:
    image: redis:7
    ports:
      - 6379:6379
    networks:
      - hshop-network
    command: redis-server --requirepass !CnJbIcJqew

  backend:
    build: .
    image: hshop_be
    ports:
      - 3000:3000
    depends_on:
      - mysql
      - redis
    networks:
      - hshop-network
    command: npm run start

volumes:
  mysql:

networks:
  hshop-network:
    driver: bridge