version: "3"

services:
  mysql:
    image: mysql:8
    environment:
      MYSQL_DATABASE: "hshop"
      MYSQL_ROOT_PASSWORD: "tF8jtP#zdz"
    ports:
      - 3306:3306
    restart: always
    networks:
      - hshop-network
    volumes:
      - mysql:/var/lib/mysql

  backend:
    build: .
    image: hshop_be
    ports:
      - 3000:3000
    depends_on:
      - mysql
    networks:
      - hshop-network
    command: npm start

volumes:
  mysql:

networks:
  hshop-network:
    driver: bridge